# Generated by Django 5.1.7 on 2025-03-14 10:04

from django.db import migrations
from datetime import datetime, timedelta

def add_initial_bookings(apps, schema_editor):
    room = apps.get_model('BuchungssystemSchulraum', 'room')
    booking = apps.get_model('BuchungssystemSchulraum', 'booking')
    user = apps.get_model('auth', 'user')

    user, created = user.objects.get_or_create(username='testuser', defaults={'password': 'testpassword'})

    room1 = room.objects.get(name='102')
    room2 = room.objects.get(name='202')

    booking.objects.create(
        room=room1,
        user=user,
        fromTime=datetime.now(),
        toTime=datetime.now() + timedelta(hours=2)
    )

    booking.objects.create(
        room=room2,
        user=user,
        fromTime=datetime.now() + timedelta(days=1),
        toTime=datetime.now() + timedelta(days=1, hours=2)
    )

def remove_initial_bookings(apps, schema_editor):
    booking = apps.get_model('BuchungssystemSchulraum', 'booking')
    user = apps.get_model('auth', 'user')

    booking.objects.filter(user__username='testuser').delete()

    user.objects.filter(username='testuser').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('BuchungssystemSchulraum', '0002_populate_rooms'),
    ]

    operations = [
        migrations.RunPython(
            add_initial_bookings,
            reverse_code=remove_initial_bookings,
            atomic=True
        ),
    ]